{"level":"error","message":"Used creation error :: WHERE parameter \"columnName\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 10:59:58"}
{"level":"error","message":"Error while getting branch Details :: WHERE parameter \"columnName\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 11:00:39"}
{"level":"error","message":"Error while getting branch Details :: WHERE parameter \"columnName\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 11:01:15"}
{"level":"error","message":"Error while getting branch Details :: WHERE parameter \"columnName\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 11:01:49"}
{"level":"error","message":"Error while getting branch Details :: WHERE parameter \"columnName\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 11:02:21"}
{"level":"error","message":"Error while getting branch Details :: column users.columnName does not exist","service":"userActivityTracking","timestamp":"2021-09-27 11:02:38"}
{"level":"error","message":"Error while getting branch Details :: column users.columnName does not exist","service":"userActivityTracking","timestamp":"2021-09-27 11:02:53"}
{"level":"error","message":"Error while getting branch Details :: column users.$columnName does not exist","service":"userActivityTracking","timestamp":"2021-09-27 11:03:17"}
{"level":"error","message":"Error while getting branch Details :: id is not defined","service":"userActivityTracking","timestamp":"2021-09-27 11:04:27"}
{"level":"error","message":"Error while getting branch Details :: column branches.columnName does not exist","service":"userActivityTracking","timestamp":"2021-09-27 11:10:24"}
{"level":"error","message":"Error while getting branch Details :: branch.remove is not a function","service":"userActivityTracking","timestamp":"2021-09-27 11:11:25"}
{"level":"error","message":"Error while getting branch Details :: branch.remove is not a function","service":"userActivityTracking","timestamp":"2021-09-27 11:11:26"}
{"level":"error","message":"Error while getting branch Details :: invalid input syntax for type integer: \"\"","service":"userActivityTracking","timestamp":"2021-09-27 11:11:52"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-27 11:11:58"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-27 11:25:05"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-27 11:25:21"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-27 11:25:22"}
{"level":"error","message":"Error while getting list of branches :: Cannot read property 'findAll' of undefined","service":"userActivityTracking","timestamp":"2021-09-27 11:27:30"}
{"level":"error","message":"Error while getting list of branches :: Cannot read property 'findAll' of undefined","service":"userActivityTracking","timestamp":"2021-09-27 11:27:38"}
{"level":"error","message":"Error while getting branch Details :: invalid input syntax for type integer: \"\"","service":"userActivityTracking","timestamp":"2021-09-27 11:32:05"}
{"level":"error","message":"Error while getting list of branches :: branch is not defined","service":"userActivityTracking","timestamp":"2021-09-27 11:36:57"}
{"level":"error","message":"Error while getting list of branches :: branch is not defined","service":"userActivityTracking","timestamp":"2021-09-27 11:37:05"}
{"level":"error","message":"Error while getting list of branches :: branchList[i].toJSONForList is not a function","service":"userActivityTracking","timestamp":"2021-09-27 11:44:09"}
{"level":"error","message":"Error while getting list of branches :: id is not defined","service":"userActivityTracking","timestamp":"2021-09-27 11:48:04"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:05:25"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:05:44"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:05:46"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:05:51"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:05:53"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:06:28"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:06:43"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:11:57"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:33:09"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:33:33"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:33:54"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:34:22"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:34:29"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:34:36"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:35:42"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:36:02"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 12:37:49"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 12:37:52"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 12:38:17"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:38:31"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:39:02"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:40:11"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:41:09"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:42:09"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:42:30"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:42:47"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:43:47"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:44:14"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:44:22"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:44:51"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:44:52"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:45:35"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:45:47"}
{"level":"error","message":"Server Start Failed listen EADDRINUSE: address already in use 127.0.0.1:3000","service":"userActivityTracking","timestamp":"2021-09-27 12:47:00"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 12:47:26"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:49:17"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:50:17"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:50:47"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:50:54"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 12:51:14"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 13:06:37"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 13:07:48"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 13:08:00"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"branch_id\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-27 13:20:46"}
{"level":"error","message":"Error while getting list of branches :: Branch doesn't exist.","service":"userActivityTracking","timestamp":"2021-09-27 13:52:09"}
{"level":"error","message":"Error while getting list of branches :: Branch doesn't exist.","service":"userActivityTracking","timestamp":"2021-09-27 13:52:17"}
{"level":"error","message":"Error while getting changeset Details :: Changeset details not found","service":"userActivityTracking","timestamp":"2021-09-27 13:58:34"}
{"level":"error","message":"Error while getting changeset Details :: changeset.dataValues.toJSON is not a function","service":"userActivityTracking","timestamp":"2021-09-27 14:02:24"}
{"level":"error","message":"Error while getting changeset Details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 14:14:54"}
{"level":"error","message":"Error while getting changeset Details :: branchId is not defined","service":"userActivityTracking","timestamp":"2021-09-27 14:15:48"}
{"level":"error","message":"Error while getting changeset Details :: branchId is not defined","service":"userActivityTracking","timestamp":"2021-09-27 14:16:06"}
{"level":"error","message":"Error while getting changeset Details :: column fileinfo.name does not exist","service":"userActivityTracking","timestamp":"2021-09-27 14:16:26"}
{"level":"error","message":"Error while getting changeset Details :: fileInfo need name to query","service":"userActivityTracking","timestamp":"2021-09-27 14:21:48"}
{"level":"error","message":"Error while getting changeset Details :: fileInfo need name to query","service":"userActivityTracking","timestamp":"2021-09-27 14:21:54"}
{"level":"error","message":"Error while getting changeset Details :: reqInfo is not defined","service":"userActivityTracking","timestamp":"2021-09-27 14:23:07"}
{"level":"error","message":"Error while getting changeset Details :: User details not found","service":"userActivityTracking","timestamp":"2021-09-27 14:23:27"}
{"level":"error","message":"Error while getting changeset Details :: User details not found","service":"userActivityTracking","timestamp":"2021-09-27 14:23:29"}
{"level":"error","message":"Error while getting changeset Details :: User details not found","service":"userActivityTracking","timestamp":"2021-09-27 14:23:33"}
{"level":"error","message":"Error while getting changeset Details :: User details not found","service":"userActivityTracking","timestamp":"2021-09-27 14:23:38"}
{"level":"error","message":"Deletion error :: update or delete on table \"branches\" violates foreign key constraint \"changesets_branch_id_fkey\" on table \"changesets\"","service":"userActivityTracking","timestamp":"2021-09-27 14:37:34"}
{"level":"error","message":"Deletion error :: update or delete on table \"branches\" violates foreign key constraint \"changesets_branch_id_fkey\" on table \"changesets\"","service":"userActivityTracking","timestamp":"2021-09-27 14:42:13"}
{"level":"error","message":"Deletion error :: update or delete on table \"branches\" violates foreign key constraint \"changesets_branch_id_fkey\" on table \"changesets\"","service":"userActivityTracking","timestamp":"2021-09-27 14:42:42"}
{"level":"error","message":"Deletion error :: update or delete on table \"branches\" violates foreign key constraint \"changesets_branch_id_fkey\" on table \"changesets\"","service":"userActivityTracking","timestamp":"2021-09-27 14:43:10"}
{"level":"error","message":"Deletion error :: null value in column \"branch_id\" violates not-null constraint","service":"userActivityTracking","timestamp":"2021-09-27 15:41:37"}
{"level":"error","message":"DB Connection Failed Unknown constraint error","service":"userActivityTracking","timestamp":"2021-09-27 15:42:29"}
{"level":"error","message":"Deletion error :: update or delete on table \"branches\" violates foreign key constraint \"fileinfos_branch_id_fkey\" on table \"fileinfos\"","service":"userActivityTracking","timestamp":"2021-09-27 15:42:43"}
{"level":"error","message":"Deletion error :: update or delete on table \"branches\" violates foreign key constraint \"fileinfos_branch_id_fkey\" on table \"fileinfos\"","service":"userActivityTracking","timestamp":"2021-09-27 15:43:18"}
{"level":"error","message":"Deletion error :: update or delete on table \"branches\" violates foreign key constraint \"fileinfos_branch_id_fkey\" on table \"fileinfos\"","service":"userActivityTracking","timestamp":"2021-09-27 15:44:48"}
{"level":"error","message":" Error occurred while checkin :: Pull request details not present.. Cannot proceed checkin","service":"userActivityTracking","timestamp":"2021-09-27 18:46:42"}
{"level":"error","message":" Error occurred while checkin :: notNull Violation: changesets.user_id cannot be null","service":"userActivityTracking","timestamp":"2021-09-27 18:53:17"}
{"level":"error","message":" Error occurred while checkin :: notNull Violation: changesets.user_id cannot be null","service":"userActivityTracking","timestamp":"2021-09-27 18:54:26"}
{"level":"error","message":" Error occurred while checkin :: file8.js not exists to update row ","service":"userActivityTracking","timestamp":"2021-09-27 18:55:19"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 18:56:01"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 18:57:25"}
{"level":"error","message":" Error occurred while checkin :: file8.js not exists to update row ","service":"userActivityTracking","timestamp":"2021-09-27 18:57:57"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:04:28"}
{"level":"error","message":" Error occurred while checkin :: file6.js not exists to update row ","service":"userActivityTracking","timestamp":"2021-09-27 19:04:52"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:05:23"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:05:59"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:06:18"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-27 19:06:53"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-27 19:06:53"}
{"level":"error","message":"Used creation error :: Validation error","service":"userActivityTracking","timestamp":"2021-09-27 19:12:56"}
{"level":"error","message":" Error occurred while checkin :: invalid input syntax for type uuid: \"-88c1-4e14-84ce-3a29d91124eb\"","service":"userActivityTracking","timestamp":"2021-09-27 19:14:09"}
{"level":"error","message":" Error occurred while checkin :: Pull request details not present.. Cannot proceed checkin","service":"userActivityTracking","timestamp":"2021-09-27 19:14:34"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-27 19:19:42"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-27 19:19:42"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:22:29"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:22:39"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-27 19:24:45"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-27 19:24:45"}
{"level":"error","message":" Error occurred while checkin :: User ID not matches with pull token.. Cannot proceed checkin","service":"userActivityTracking","timestamp":"2021-09-27 19:25:16"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:25:19"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-27 19:25:39"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-27 19:25:39"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-27 19:25:52"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 20:49:46"}
{"level":"error","message":"Error while updating user details :: obj is not defined","service":"userActivityTracking","timestamp":"2021-09-27 20:52:00"}
{"level":"error","message":"Error while updating user details :: reqInfo.hasOwnProperty is not a function","service":"userActivityTracking","timestamp":"2021-09-27 20:52:25"}
{"level":"error","message":"Error while updating user details :: reqInfo.hasOwnProperty is not a function","service":"userActivityTracking","timestamp":"2021-09-27 20:53:09"}
{"level":"error","message":"Error while updating user details :: reqInfo.hasOwnProperty is not a function","service":"userActivityTracking","timestamp":"2021-09-27 20:53:45"}
{"level":"error","message":"Error while updating user details :: reqInfo.hasOwnProperty is not a function","service":"userActivityTracking","timestamp":"2021-09-27 20:53:56"}
{"level":"error","message":"Error while updating user details :: Cannot convert object to primitive value","service":"userActivityTracking","timestamp":"2021-09-27 20:54:19"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 20:55:23"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 20:55:39"}
{"level":"error","message":"Error while updating user details :: updateValues.set is not a function","service":"userActivityTracking","timestamp":"2021-09-27 20:58:52"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 20:59:50"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 21:00:27"}
{"level":"error","message":"Error while updating user details :: column \"userId\" does not exist","service":"userActivityTracking","timestamp":"2021-09-27 21:00:46"}
{"level":"error","message":"Error while updating user details :: column \"userId\" does not exist","service":"userActivityTracking","timestamp":"2021-09-27 21:01:34"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 21:02:01"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 21:02:30"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 21:02:36"}
{"level":"error","message":"Error while updating user details :: Cannot convert undefined or null to object","service":"userActivityTracking","timestamp":"2021-09-27 21:03:02"}
{"level":"error","message":"Error while updating user details :: updateValues.length is not a function","service":"userActivityTracking","timestamp":"2021-09-27 21:05:06"}
{"level":"error","message":"Error while updating user details :: Cannot read property 'length' of undefined","service":"userActivityTracking","timestamp":"2021-09-27 21:05:28"}
{"level":"error","message":"Error while updating user details :: Update value must be mentioned","service":"userActivityTracking","timestamp":"2021-09-27 21:11:06"}
{"level":"error","message":"Error while getting list of branches :: User info is not present.","service":"userActivityTracking","timestamp":"2021-09-27 21:15:46"}
{"level":"error","message":"Error while getting list of branches :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 21:15:57"}
{"level":"error","message":"Error while getting list of branches :: User info is not present.","service":"userActivityTracking","timestamp":"2021-09-27 21:16:03"}
{"level":"error","message":"Error while getting list of branches :: User info is not present.","service":"userActivityTracking","timestamp":"2021-09-27 21:16:23"}
{"level":"error","message":"Error while updating user details :: invalid input syntax for type integer: \"[object Object]\"","service":"userActivityTracking","timestamp":"2021-09-27 21:24:39"}
{"level":"error","message":"Error while updating user details :: Op is not defined","service":"userActivityTracking","timestamp":"2021-09-27 21:27:26"}
{"level":"error","message":"Error while getting changeset Details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 23:34:35"}
{"level":"error","message":"Error while getting changeset Details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-27 23:34:38"}
{"level":"error","message":"Error while getting changeset Details :: changeset ID needed to query","service":"userActivityTracking","timestamp":"2021-09-27 23:36:35"}
{"level":"error","message":"Error while getting changeset Details :: changeset ID needed to query","service":"userActivityTracking","timestamp":"2021-09-27 23:36:38"}
{"level":"error","message":"Server Start Failed server.validator is not a function","service":"userActivityTracking","timestamp":"2021-09-28 07:50:44"}
{"level":"error","message":"Branch creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"branches\" (\"id\",\"name\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3) RETURNING \"id\",\"name\",\"description\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-28 10:37:03"}
{"level":"error","message":"Branch creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"branches\" (\"id\",\"name\",\"description\",\"createdAt\",\"updatedAt\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"name\",\"description\",\"createdAt\",\"updatedAt\";","service":"userActivityTracking","timestamp":"2021-09-28 10:43:06"}
{"level":"error","message":"File creation error :: Validation error ::SequelizeUniqueConstraintError  :: INSERT INTO \"fileinfos\" (\"id\",\"filename\",\"createdAt\",\"updatedAt\",\"branchId\") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING \"id\",\"filename\",\"createdAt\",\"updatedAt\",\"branchId\";","service":"userActivityTracking","timestamp":"2021-09-28 12:08:54"}
{"level":"error","message":"Error while getting changeset Details :: fileInfo need name to query","service":"userActivityTracking","timestamp":"2021-09-28 12:23:15"}
{"level":"error","message":"Error while getting changeset Details :: fileInfo need name to query","service":"userActivityTracking","timestamp":"2021-09-28 12:24:02"}
{"level":"error","message":"Error while getting changeset Details :: fileInfo need name to query","service":"userActivityTracking","timestamp":"2021-09-28 12:24:08"}
{"level":"error","message":"Error while updating branch details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 12:41:35"}
{"level":"error","message":"Error while updating branch details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 12:43:06"}
{"level":"error","message":"Error while updating branch details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 12:43:15"}
{"level":"error","message":"Error while updating branch details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 12:43:33"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:56:07"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:56:08"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:56:15"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:56:18"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:57:03"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:57:04"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:57:59"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:58:22"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:58:25"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:58:45"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:58:52"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:58:55"}
{"level":"error","message":"Error while getting branch Details :: branch ID or name must be present to query","service":"userActivityTracking","timestamp":"2021-09-28 12:59:11"}
{"level":"error","message":"Used creation error :: Validation error","service":"userActivityTracking","timestamp":"2021-09-28 16:19:40"}
{"level":"error","message":"Used creation error :: Validation error","service":"userActivityTracking","timestamp":"2021-09-28 16:20:22"}
{"level":"error","message":"Used creation error :: Validation error","service":"userActivityTracking","timestamp":"2021-09-28 16:33:37"}
{"level":"error","message":"Used creation error :: Validation error","service":"userActivityTracking","timestamp":"2021-09-28 16:36:52"}
{"level":"error","message":"Used creation error :: Validation error","service":"userActivityTracking","timestamp":"2021-09-28 16:37:05"}
{"level":"error","message":"Error while getting changeset Details :: User ID needed to query","service":"userActivityTracking","timestamp":"2021-09-28 16:44:19"}
{"level":"error","message":"Error while getting changeset Details :: User ID needed to query","service":"userActivityTracking","timestamp":"2021-09-28 16:45:04"}
{"level":"error","message":"Error while getting changeset Details :: User ID needed to query","service":"userActivityTracking","timestamp":"2021-09-28 16:45:05"}
{"level":"error","message":"Error while getting changeset Details :: User details not found","service":"userActivityTracking","timestamp":"2021-09-28 16:48:31"}
{"level":"error","message":"Error while updating user details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 16:55:18"}
{"level":"error","message":"Error while updating user details :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 16:58:10"}
{"level":"error","message":" Error occurred while checkin :: Pull request details not present.. Cannot proceed checkin","service":"userActivityTracking","timestamp":"2021-09-28 17:16:32"}
{"level":"error","message":" Error occurred while checkin :: invalid input syntax for type uuid: \" 1\"","service":"userActivityTracking","timestamp":"2021-09-28 17:16:58"}
{"level":"error","message":" Error occurred while checkin :: Push failed due to time conflict. Please try after pull and update","service":"userActivityTracking","timestamp":"2021-09-28 17:17:26"}
{"level":"error","message":" Error occurred while checkin :: WHERE parameter \"pull_token\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 17:18:09"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-28 17:34:55"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-28 17:34:55"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-28 18:30:12"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-28 18:30:12"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-28 18:30:17"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-28 18:30:17"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-28 18:30:36"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-28 18:30:36"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-28 18:30:43"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-28 18:30:43"}
{"level":"error","message":"File name already exists in DB","service":"userActivityTracking","timestamp":"2021-09-28 18:30:46"}
{"level":"error","message":" Error occurred while checkin :: File name must be uniqe. Duplicate file name entered for new file addition","service":"userActivityTracking","timestamp":"2021-09-28 18:30:46"}
{"level":"error","message":"Error while getting list of branches :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 18:35:14"}
{"level":"error","message":"Error while getting list of branches :: WHERE parameter \"id\" has invalid \"undefined\" value","service":"userActivityTracking","timestamp":"2021-09-28 18:35:49"}
{"level":"error","message":"Error while getting changeset Details :: Changeset details not found","service":"userActivityTracking","timestamp":"2021-09-28 18:37:59"}
{"level":"error","message":"Error while getting changeset Details :: changeset ID needed to query","service":"userActivityTracking","timestamp":"2021-09-28 18:47:40"}
{"level":"error","message":"Error while getting changeset Details :: dataValues is not defined","service":"userActivityTracking","timestamp":"2021-09-28 18:50:40"}
